### ISSUE TITLE
' Double-Helix Hologram ' This file won't open!  

### ISSUE THREAD

**Issue by wangdada8066** [ralfmouthaan/DoubleHelixPSF#1]
' Double-Helix Hologram ' This file won't open!  ，Is there a code for text formatting？

**Comment by ralfmouthaan** [comment]
Hi Wangdada, 

This repository is only public so that I could share it with a collaborator - I am not completely happy with the code. Specifically, I have my reservations about some of the convergent behaviour of the code, and while I think the hologram generated does give a double helix, I am not sure it is the "best" double helix. Having said that, feel free to have a look.

The "Double Helix Hologram.m" should actually be a .mat file, but was incorrectly saved. The way to open it is to drag and drop it into your Matlab workspace. The same information is shown in the "Double Helix Hologram.png" image in the same folder.

Ralf.

**Comment by wangdada8066** [comment]
Hello, thank you very much for your last answer!I have one more question:"A constraint is phase propagation only, how is this represented?"

**Comment by ralfmouthaan** [comment]
Hi Wangdada,

I'm not sure I understand your question. Propagation is described by convolution with a kernel corresponding to the angular spectrum method. This affects both the amplitude and phase of the beam. The hologram is phase-only, meaning it only modulates the phase of the beam, and not the amplitude. This is because it is designed to be displayed on a nematic liquid crystal spatial light modulator or a glass (?) mask.

Ralf.

**Comment by wangdada8066** [comment]
Hi  Ralf,
Why is the image gone when x takes the value "x=linspace(-1e-4,1e-4,Nx)"?What is the size of the image size related to?  Isn't the power boost higher by changing the function of mask?
Wangdada
